name: 'Enhance Integration Tests'
author: 'Enhance Team'
description: 'GitHub Action for running integration tests on Enhance'

inputs:
  use_local_package:
    description: 'Install the local github package for testing'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          repository: enhance-dev/actions
          path: integration-tests

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Create Starter Project
        shell: bash
        run: npx "@enhance/cli@latest" new ./myproject -y

      - name: npm install
        shell: bash
        run: npm install @architect/sandbox tap-arc tape tiny-json-http

      - name: Test
        shell: bash
        run: npx tape 'integration-tests/test/**/*-test.mjs' | npx tap-arc
